import { MigrationInterface, QueryRunner } from "typeorm";

export class SchemaUpdate1732274112466 implements MigrationInterface {
    name = 'SchemaUpdate1732274112466'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`state\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(191) NOT NULL, \`abbreviation\` varchar(191) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`collective_purchase\` (\`id\` int NOT NULL AUTO_INCREMENT, \`products\` json NOT NULL, \`description\` text NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`city_id\` int NOT NULL, \`cooperative_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversation_message\` (\`id\` int NOT NULL AUTO_INCREMENT, \`content\` text NOT NULL, \`seen\` tinyint NOT NULL DEFAULT 0, \`cooperative_id\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`status\` enum ('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending', \`revised_at\` timestamp NULL, \`conversation_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversation\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`last_message\` timestamp NULL, \`is_direct\` tinyint NOT NULL DEFAULT 0, \`initiator_cooperative_id\` int NOT NULL, \`participant_cooperative_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cooperative_debit\` (\`id\` int NOT NULL AUTO_INCREMENT, \`cooperative_id\` int NOT NULL, \`amount\` decimal(10,2) NOT NULL, \`description\` varchar(255) NOT NULL, \`status\` enum ('pending', 'paid', 'canceled') NOT NULL DEFAULT 'pending', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`auth_token\` (\`id\` int NOT NULL AUTO_INCREMENT, \`token\` varchar(255) NOT NULL, \`expires_at\` datetime NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`user_Id\` int NOT NULL, UNIQUE INDEX \`IDX_7a74281711d1a581b4dcc4d59f\` (\`token\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reset_password\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`token\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`expires_at\` datetime NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`id\` int NOT NULL AUTO_INCREMENT, \`username\` varchar(191) NOT NULL, \`password\` varchar(191) NOT NULL, \`role\` enum ('ADMIN', 'COOPERATIVE', 'DRIVER', 'VISITANT') NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_78a916df40e02a9deb1c4b75ed\` (\`username\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`driver\` (\`id\` int NOT NULL AUTO_INCREMENT, \`cooperative_id\` int NOT NULL, \`user_id\` int NOT NULL, \`name\` varchar(255) NOT NULL, \`phone\` varchar(255) NOT NULL, \`cpf\` varchar(255) NOT NULL, \`cnh_category\` enum ('ACC', 'A', 'B', 'C', 'D', 'E', 'AB', 'AC', 'AD', 'AE') NOT NULL, \`number_cnh\` varchar(255) NOT NULL, \`blood_type\` enum ('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG') NOT NULL, \`security_contact\` varchar(255) NOT NULL, \`date_birth\` date NOT NULL, \`img\` varchar(255) NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_3ef4d0634977aa36f7255231e6\` (\`cpf\`), UNIQUE INDEX \`REL_732fa4b746b5fd36d24e72576e\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vehicle_type\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`mpy\` decimal(5,2) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vehicle\` (\`id\` int NOT NULL AUTO_INCREMENT, \`license_plate\` varchar(255) NOT NULL, \`model\` varchar(255) NOT NULL, \`img\` varchar(255) NULL, \`volume\` float NOT NULL, \`maximum_weight\` float NOT NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`cooperative_id\` int NOT NULL, \`type_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`packaging\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`catalog_packaging\` (\`id\` int NOT NULL AUTO_INCREMENT, \`packaging_id\` int NOT NULL, \`info\` text NOT NULL, \`weight\` float NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`type\` enum ('PRIMARY', 'SECONDARY', 'ADDITIONAL') NOT NULL, \`catalog_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`catalog_seasonality\` (\`id\` int NOT NULL AUTO_INCREMENT, \`catalog_id\` int NOT NULL, \`month\` int NOT NULL, \`seasonality\` enum ('NONE', 'LOW', 'MEDIUM', 'HIGH') NOT NULL DEFAULT 'NONE', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`catalog\` (\`id\` int NOT NULL AUTO_INCREMENT, \`cooperative_id\` int NOT NULL, \`product_id\` int NOT NULL, \`has_seasonality\` tinyint NOT NULL DEFAULT 0, \`high_estimate\` float NULL, \`medium_estimate\` float NULL, \`low_estimate\` float NULL, \`has_primary_packaging\` tinyint NOT NULL DEFAULT 0, \`has_secondary_packaging\` tinyint NOT NULL DEFAULT 0, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_category\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_type\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`mpy\` decimal(5,2) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`product_type_id\` int NOT NULL, \`product_category_id\` int NOT NULL, \`img\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`travel_route_product\` (\`id\` int NOT NULL AUTO_INCREMENT, \`product_id\` int NOT NULL, \`loaded_weight\` decimal(10,2) NOT NULL DEFAULT '0.00', \`unloaded_weight\` decimal(10,2) NOT NULL DEFAULT '0.00', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`route_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`travel_route\` (\`id\` int NOT NULL AUTO_INCREMENT, \`travel_id\` int NOT NULL, \`address\` varchar(255) NOT NULL, \`latitude\` decimal(10,8) NOT NULL, \`longitude\` decimal(10,8) NOT NULL, \`order\` int NOT NULL DEFAULT '0', \`distance\` decimal(10,3) NOT NULL, \`loading_weight\` decimal(10,2) NOT NULL, \`unloading_weight\` decimal(10,2) NOT NULL, \`offer_id\` int NULL, \`arrived_at\` timestamp NULL, \`attachment\` varchar(255) NULL, \`coop_attachment\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`travel\` (\`id\` int NOT NULL AUTO_INCREMENT, \`start_date_time\` timestamp NOT NULL, \`status\` enum ('awaiting', 'completed', 'canceled', 'in_progress') NOT NULL DEFAULT 'awaiting', \`driver_id\` int NOT NULL, \`vehicle_id\` int NOT NULL, \`cooperative_id\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`travel_offer\` (\`id\` int NOT NULL AUTO_INCREMENT, \`cooperative_id\` int NOT NULL, \`status\` enum ('awaiting', 'confirmed', 'rejected', 'negotiating', 'confirmedPendingRoutes') NOT NULL DEFAULT 'awaiting', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`changelogs\` json NULL, \`travel_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`business\` (\`id\` int NOT NULL AUTO_INCREMENT, \`requesting_cooperative_id\` int NOT NULL, \`offering_cooperative_id\` int NOT NULL, \`travel_offer_id\` int NULL, \`debit_id\` int NULL, \`fee\` decimal(10,2) NOT NULL, \`type\` enum ('CC', 'BN', 'V') NOT NULL, \`status\` enum ('negotiating', 'confirmed', 'done', 'canceled') NOT NULL DEFAULT 'negotiating', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`collective_purchase_id\` int NULL, \`business_desk_id\` int NULL, \`conversation_id\` int NOT NULL, UNIQUE INDEX \`REL_c73702e82a4486177fc4be9421\` (\`debit_id\`), UNIQUE INDEX \`REL_d5944b36b96ee08d3ce9d2a6c9\` (\`conversation_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`business_desk_product\` (\`id\` int NOT NULL AUTO_INCREMENT, \`weight\` float NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`business_desk_id\` int NOT NULL, \`product_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`business_desk\` (\`id\` int NOT NULL AUTO_INCREMENT, \`description\` text NOT NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`cooperative_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cooperative\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`company_name\` varchar(255) NOT NULL, \`fantasy_name\` varchar(255) NULL, \`email\` varchar(255) NOT NULL, \`description\` mediumtext NULL, \`cnpj\` varchar(255) NULL, \`website\` varchar(255) NULL, \`phone\` varchar(255) NULL, \`instagram\` varchar(255) NULL, \`facebook\` varchar(255) NULL, \`city_id\` int NULL, \`street\` varchar(255) NULL, \`cep\` varchar(255) NULL, \`number\` varchar(255) NULL, \`neighborhood\` varchar(255) NULL, \`complement\` varchar(255) NULL, \`img\` varchar(255) NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`registration_completed_at\` timestamp NULL, UNIQUE INDEX \`IDX_2a69d61de839a24cee7bcd4a12\` (\`email\`), UNIQUE INDEX \`REL_d0686166477ff5206fb4e01bad\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`city\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(191) NOT NULL, \`state_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`visitant\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`phone\` varchar(255) NOT NULL, \`address\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`cep\` varchar(255) NOT NULL, \`number\` varchar(255) NOT NULL, \`neighborhood\` varchar(255) NOT NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`city_id\` int NULL, \`user_id\` int NULL, UNIQUE INDEX \`IDX_65383015600da0e0adebcf6f1f\` (\`email\`), UNIQUE INDEX \`REL_db009d693d10bc8f16b163e0a3\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notification\` (\`id\` int NOT NULL AUTO_INCREMENT, \`message\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`type\` enum ('new_message', 'business_desk', 'collective_purchase', 'travel_offer') NOT NULL, \`is_read\` tinyint NOT NULL DEFAULT 0, \`cooperative_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`faq\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` text NOT NULL, \`content\` text NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`config_system\` (\`id\` int NOT NULL AUTO_INCREMENT, \`service_tax\` decimal(5,2) NOT NULL, \`km_cost\` decimal(10,2) NOT NULL, \`mpy_load\` decimal(5,2) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`access_request\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`cnpj\` varchar(255) NOT NULL, \`address\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`phone\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`collective_purchase\` ADD CONSTRAINT \`FK_cf73255f1038d51155851ae400d\` FOREIGN KEY (\`city_id\`) REFERENCES \`city\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`collective_purchase\` ADD CONSTRAINT \`FK_32813bc2964359ea4325fec3f0d\` FOREIGN KEY (\`cooperative_id\`) REFERENCES \`cooperative\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_message\` ADD CONSTRAINT \`FK_fde1a45d37dfea0608d6f6166a7\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversation\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_message\` ADD CONSTRAINT \`FK_1c6dcf425888f0fb51891a1d33d\` FOREIGN KEY (\`cooperative_id\`) REFERENCES \`cooperative\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation\` ADD CONSTRAINT \`FK_f154e60b475b45c5afeba85b888\` FOREIGN KEY (\`initiator_cooperative_id\`) REFERENCES \`cooperative\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation\` ADD CONSTRAINT \`FK_ee8d3829876f4c3f72eb2b01fff\` FOREIGN KEY (\`participant_cooperative_id\`) REFERENCES \`cooperative\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cooperative_debit\` ADD CONSTRAINT \`FK_494bc582f20c761666ac36e3b2c\` FOREIGN KEY (\`cooperative_id\`) REFERENCES \`cooperative\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`auth_token\` ADD CONSTRAINT \`FK_f3e1cb55107c78cc7015a79fa5f\` FOREIGN KEY (\`user_Id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reset_password\` ADD CONSTRAINT \`FK_de65040d842349a5e6428ff21e6\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`driver\` ADD CONSTRAINT \`FK_732fa4b746b5fd36d24e72576e7\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`driver\` ADD CONSTRAINT \`FK_db120282ac9af48df160d20df6c\` FOREIGN KEY (\`cooperative_id\`) REFERENCES \`cooperative\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` ADD CONSTRAINT \`FK_bd8f8f7f8bb10aaaf49f087ec6d\` FOREIGN KEY (\`cooperative_id\`) REFERENCES \`cooperative\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` ADD CONSTRAINT \`FK_465137c10960b54f82f1b145e43\` FOREIGN KEY (\`type_id\`) REFERENCES \`vehicle_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`catalog_packaging\` ADD CONSTRAINT \`FK_9fc54a925cff02f0b06fbb34cd5\` FOREIGN KEY (\`catalog_id\`) REFERENCES \`catalog\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`catalog_packaging\` ADD CONSTRAINT \`FK_59819944d36bf32370ff06b8e29\` FOREIGN KEY (\`packaging_id\`) REFERENCES \`packaging\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`catalog_seasonality\` ADD CONSTRAINT \`FK_b8693925dca308b241d31301591\` FOREIGN KEY (\`catalog_id\`) REFERENCES \`catalog\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`catalog\` ADD CONSTRAINT \`FK_651b802b35745d02f3e73a31d91\` FOREIGN KEY (\`cooperative_id\`) REFERENCES \`cooperative\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`catalog\` ADD CONSTRAINT \`FK_95f45f9c8a51980c2eb98d4532e\` FOREIGN KEY (\`product_id\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product\` ADD CONSTRAINT \`FK_9c47355777d0ea7c76aa31059cd\` FOREIGN KEY (\`product_type_id\`) REFERENCES \`product_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product\` ADD CONSTRAINT \`FK_c385a97195418da0bd3a08ceced\` FOREIGN KEY (\`product_category_id\`) REFERENCES \`product_category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`travel_route_product\` ADD CONSTRAINT \`FK_fb4deccae406ee1d95f1dae465f\` FOREIGN KEY (\`route_id\`) REFERENCES \`travel_route\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`travel_route_product\` ADD CONSTRAINT \`FK_e809f0c04cd9505868d8f63434d\` FOREIGN KEY (\`product_id\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`travel_route\` ADD CONSTRAINT \`FK_1ac265d2b00144419cb707331a1\` FOREIGN KEY (\`travel_id\`) REFERENCES \`travel\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`travel_route\` ADD CONSTRAINT \`FK_3bf876190069e02e6a05ef6ee14\` FOREIGN KEY (\`offer_id\`) REFERENCES \`travel_offer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`travel\` ADD CONSTRAINT \`FK_a5b3201aafa3cac53a5b2b3b946\` FOREIGN KEY (\`driver_id\`) REFERENCES \`driver\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`travel\` ADD CONSTRAINT \`FK_6f7852d8c7d2efd9ce279a35d5c\` FOREIGN KEY (\`vehicle_id\`) REFERENCES \`vehicle\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`travel\` ADD CONSTRAINT \`FK_866ec1b9f3a85cea4392827d585\` FOREIGN KEY (\`cooperative_id\`) REFERENCES \`cooperative\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`travel_offer\` ADD CONSTRAINT \`FK_63fade497a9fccda1dd4447a485\` FOREIGN KEY (\`travel_id\`) REFERENCES \`travel\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`travel_offer\` ADD CONSTRAINT \`FK_39f34c91175691545a900514ac0\` FOREIGN KEY (\`cooperative_id\`) REFERENCES \`cooperative\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business\` ADD CONSTRAINT \`FK_9b5abac8cbffc3d2c704c6609ae\` FOREIGN KEY (\`offering_cooperative_id\`) REFERENCES \`cooperative\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business\` ADD CONSTRAINT \`FK_0108da13662327bff37a0cb65ad\` FOREIGN KEY (\`requesting_cooperative_id\`) REFERENCES \`cooperative\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business\` ADD CONSTRAINT \`FK_534ed8159eae14c43a97efc89f3\` FOREIGN KEY (\`travel_offer_id\`) REFERENCES \`travel_offer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business\` ADD CONSTRAINT \`FK_14dad1350674761a3cf1e865296\` FOREIGN KEY (\`collective_purchase_id\`) REFERENCES \`collective_purchase\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business\` ADD CONSTRAINT \`FK_c73702e82a4486177fc4be94213\` FOREIGN KEY (\`debit_id\`) REFERENCES \`cooperative_debit\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business\` ADD CONSTRAINT \`FK_e3b1297a3ccccb5b54f8ae95ba5\` FOREIGN KEY (\`business_desk_id\`) REFERENCES \`business_desk\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business\` ADD CONSTRAINT \`FK_d5944b36b96ee08d3ce9d2a6c97\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversation\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_desk_product\` ADD CONSTRAINT \`FK_12e1ad606583e2730a447f5092f\` FOREIGN KEY (\`business_desk_id\`) REFERENCES \`business_desk\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_desk_product\` ADD CONSTRAINT \`FK_faddd59dfc53eefaac4f96aa5b8\` FOREIGN KEY (\`product_id\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`business_desk\` ADD CONSTRAINT \`FK_880e9c574e91168d6a5c84a0f80\` FOREIGN KEY (\`cooperative_id\`) REFERENCES \`cooperative\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cooperative\` ADD CONSTRAINT \`FK_09a85ae5b6957f83a31577aab2f\` FOREIGN KEY (\`city_id\`) REFERENCES \`city\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cooperative\` ADD CONSTRAINT \`FK_d0686166477ff5206fb4e01bad2\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`city\` ADD CONSTRAINT \`FK_37ecd8addf395545dcb0242a593\` FOREIGN KEY (\`state_id\`) REFERENCES \`state\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`visitant\` ADD CONSTRAINT \`FK_ee8c07d0a56dfdca28c686eb97f\` FOREIGN KEY (\`city_id\`) REFERENCES \`city\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`visitant\` ADD CONSTRAINT \`FK_db009d693d10bc8f16b163e0a33\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notification\` ADD CONSTRAINT \`FK_72f63ea1c2f55ae6cd57dccd4b8\` FOREIGN KEY (\`cooperative_id\`) REFERENCES \`cooperative\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`notification\` DROP FOREIGN KEY \`FK_72f63ea1c2f55ae6cd57dccd4b8\``);
        await queryRunner.query(`ALTER TABLE \`visitant\` DROP FOREIGN KEY \`FK_db009d693d10bc8f16b163e0a33\``);
        await queryRunner.query(`ALTER TABLE \`visitant\` DROP FOREIGN KEY \`FK_ee8c07d0a56dfdca28c686eb97f\``);
        await queryRunner.query(`ALTER TABLE \`city\` DROP FOREIGN KEY \`FK_37ecd8addf395545dcb0242a593\``);
        await queryRunner.query(`ALTER TABLE \`cooperative\` DROP FOREIGN KEY \`FK_d0686166477ff5206fb4e01bad2\``);
        await queryRunner.query(`ALTER TABLE \`cooperative\` DROP FOREIGN KEY \`FK_09a85ae5b6957f83a31577aab2f\``);
        await queryRunner.query(`ALTER TABLE \`business_desk\` DROP FOREIGN KEY \`FK_880e9c574e91168d6a5c84a0f80\``);
        await queryRunner.query(`ALTER TABLE \`business_desk_product\` DROP FOREIGN KEY \`FK_faddd59dfc53eefaac4f96aa5b8\``);
        await queryRunner.query(`ALTER TABLE \`business_desk_product\` DROP FOREIGN KEY \`FK_12e1ad606583e2730a447f5092f\``);
        await queryRunner.query(`ALTER TABLE \`business\` DROP FOREIGN KEY \`FK_d5944b36b96ee08d3ce9d2a6c97\``);
        await queryRunner.query(`ALTER TABLE \`business\` DROP FOREIGN KEY \`FK_e3b1297a3ccccb5b54f8ae95ba5\``);
        await queryRunner.query(`ALTER TABLE \`business\` DROP FOREIGN KEY \`FK_c73702e82a4486177fc4be94213\``);
        await queryRunner.query(`ALTER TABLE \`business\` DROP FOREIGN KEY \`FK_14dad1350674761a3cf1e865296\``);
        await queryRunner.query(`ALTER TABLE \`business\` DROP FOREIGN KEY \`FK_534ed8159eae14c43a97efc89f3\``);
        await queryRunner.query(`ALTER TABLE \`business\` DROP FOREIGN KEY \`FK_0108da13662327bff37a0cb65ad\``);
        await queryRunner.query(`ALTER TABLE \`business\` DROP FOREIGN KEY \`FK_9b5abac8cbffc3d2c704c6609ae\``);
        await queryRunner.query(`ALTER TABLE \`travel_offer\` DROP FOREIGN KEY \`FK_39f34c91175691545a900514ac0\``);
        await queryRunner.query(`ALTER TABLE \`travel_offer\` DROP FOREIGN KEY \`FK_63fade497a9fccda1dd4447a485\``);
        await queryRunner.query(`ALTER TABLE \`travel\` DROP FOREIGN KEY \`FK_866ec1b9f3a85cea4392827d585\``);
        await queryRunner.query(`ALTER TABLE \`travel\` DROP FOREIGN KEY \`FK_6f7852d8c7d2efd9ce279a35d5c\``);
        await queryRunner.query(`ALTER TABLE \`travel\` DROP FOREIGN KEY \`FK_a5b3201aafa3cac53a5b2b3b946\``);
        await queryRunner.query(`ALTER TABLE \`travel_route\` DROP FOREIGN KEY \`FK_3bf876190069e02e6a05ef6ee14\``);
        await queryRunner.query(`ALTER TABLE \`travel_route\` DROP FOREIGN KEY \`FK_1ac265d2b00144419cb707331a1\``);
        await queryRunner.query(`ALTER TABLE \`travel_route_product\` DROP FOREIGN KEY \`FK_e809f0c04cd9505868d8f63434d\``);
        await queryRunner.query(`ALTER TABLE \`travel_route_product\` DROP FOREIGN KEY \`FK_fb4deccae406ee1d95f1dae465f\``);
        await queryRunner.query(`ALTER TABLE \`product\` DROP FOREIGN KEY \`FK_c385a97195418da0bd3a08ceced\``);
        await queryRunner.query(`ALTER TABLE \`product\` DROP FOREIGN KEY \`FK_9c47355777d0ea7c76aa31059cd\``);
        await queryRunner.query(`ALTER TABLE \`catalog\` DROP FOREIGN KEY \`FK_95f45f9c8a51980c2eb98d4532e\``);
        await queryRunner.query(`ALTER TABLE \`catalog\` DROP FOREIGN KEY \`FK_651b802b35745d02f3e73a31d91\``);
        await queryRunner.query(`ALTER TABLE \`catalog_seasonality\` DROP FOREIGN KEY \`FK_b8693925dca308b241d31301591\``);
        await queryRunner.query(`ALTER TABLE \`catalog_packaging\` DROP FOREIGN KEY \`FK_59819944d36bf32370ff06b8e29\``);
        await queryRunner.query(`ALTER TABLE \`catalog_packaging\` DROP FOREIGN KEY \`FK_9fc54a925cff02f0b06fbb34cd5\``);
        await queryRunner.query(`ALTER TABLE \`vehicle\` DROP FOREIGN KEY \`FK_465137c10960b54f82f1b145e43\``);
        await queryRunner.query(`ALTER TABLE \`vehicle\` DROP FOREIGN KEY \`FK_bd8f8f7f8bb10aaaf49f087ec6d\``);
        await queryRunner.query(`ALTER TABLE \`driver\` DROP FOREIGN KEY \`FK_db120282ac9af48df160d20df6c\``);
        await queryRunner.query(`ALTER TABLE \`driver\` DROP FOREIGN KEY \`FK_732fa4b746b5fd36d24e72576e7\``);
        await queryRunner.query(`ALTER TABLE \`reset_password\` DROP FOREIGN KEY \`FK_de65040d842349a5e6428ff21e6\``);
        await queryRunner.query(`ALTER TABLE \`auth_token\` DROP FOREIGN KEY \`FK_f3e1cb55107c78cc7015a79fa5f\``);
        await queryRunner.query(`ALTER TABLE \`cooperative_debit\` DROP FOREIGN KEY \`FK_494bc582f20c761666ac36e3b2c\``);
        await queryRunner.query(`ALTER TABLE \`conversation\` DROP FOREIGN KEY \`FK_ee8d3829876f4c3f72eb2b01fff\``);
        await queryRunner.query(`ALTER TABLE \`conversation\` DROP FOREIGN KEY \`FK_f154e60b475b45c5afeba85b888\``);
        await queryRunner.query(`ALTER TABLE \`conversation_message\` DROP FOREIGN KEY \`FK_1c6dcf425888f0fb51891a1d33d\``);
        await queryRunner.query(`ALTER TABLE \`conversation_message\` DROP FOREIGN KEY \`FK_fde1a45d37dfea0608d6f6166a7\``);
        await queryRunner.query(`ALTER TABLE \`collective_purchase\` DROP FOREIGN KEY \`FK_32813bc2964359ea4325fec3f0d\``);
        await queryRunner.query(`ALTER TABLE \`collective_purchase\` DROP FOREIGN KEY \`FK_cf73255f1038d51155851ae400d\``);
        await queryRunner.query(`DROP TABLE \`access_request\``);
        await queryRunner.query(`DROP TABLE \`config_system\``);
        await queryRunner.query(`DROP TABLE \`faq\``);
        await queryRunner.query(`DROP TABLE \`notification\``);
        await queryRunner.query(`DROP INDEX \`REL_db009d693d10bc8f16b163e0a3\` ON \`visitant\``);
        await queryRunner.query(`DROP INDEX \`IDX_65383015600da0e0adebcf6f1f\` ON \`visitant\``);
        await queryRunner.query(`DROP TABLE \`visitant\``);
        await queryRunner.query(`DROP TABLE \`city\``);
        await queryRunner.query(`DROP INDEX \`REL_d0686166477ff5206fb4e01bad\` ON \`cooperative\``);
        await queryRunner.query(`DROP INDEX \`IDX_2a69d61de839a24cee7bcd4a12\` ON \`cooperative\``);
        await queryRunner.query(`DROP TABLE \`cooperative\``);
        await queryRunner.query(`DROP TABLE \`business_desk\``);
        await queryRunner.query(`DROP TABLE \`business_desk_product\``);
        await queryRunner.query(`DROP INDEX \`REL_d5944b36b96ee08d3ce9d2a6c9\` ON \`business\``);
        await queryRunner.query(`DROP INDEX \`REL_c73702e82a4486177fc4be9421\` ON \`business\``);
        await queryRunner.query(`DROP TABLE \`business\``);
        await queryRunner.query(`DROP TABLE \`travel_offer\``);
        await queryRunner.query(`DROP TABLE \`travel\``);
        await queryRunner.query(`DROP TABLE \`travel_route\``);
        await queryRunner.query(`DROP TABLE \`travel_route_product\``);
        await queryRunner.query(`DROP TABLE \`product\``);
        await queryRunner.query(`DROP TABLE \`product_type\``);
        await queryRunner.query(`DROP TABLE \`product_category\``);
        await queryRunner.query(`DROP TABLE \`catalog\``);
        await queryRunner.query(`DROP TABLE \`catalog_seasonality\``);
        await queryRunner.query(`DROP TABLE \`catalog_packaging\``);
        await queryRunner.query(`DROP TABLE \`packaging\``);
        await queryRunner.query(`DROP TABLE \`vehicle\``);
        await queryRunner.query(`DROP TABLE \`vehicle_type\``);
        await queryRunner.query(`DROP INDEX \`REL_732fa4b746b5fd36d24e72576e\` ON \`driver\``);
        await queryRunner.query(`DROP INDEX \`IDX_3ef4d0634977aa36f7255231e6\` ON \`driver\``);
        await queryRunner.query(`DROP TABLE \`driver\``);
        await queryRunner.query(`DROP INDEX \`IDX_78a916df40e02a9deb1c4b75ed\` ON \`user\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP TABLE \`reset_password\``);
        await queryRunner.query(`DROP INDEX \`IDX_7a74281711d1a581b4dcc4d59f\` ON \`auth_token\``);
        await queryRunner.query(`DROP TABLE \`auth_token\``);
        await queryRunner.query(`DROP TABLE \`cooperative_debit\``);
        await queryRunner.query(`DROP TABLE \`conversation\``);
        await queryRunner.query(`DROP TABLE \`conversation_message\``);
        await queryRunner.query(`DROP TABLE \`collective_purchase\``);
        await queryRunner.query(`DROP TABLE \`state\``);
    }

}
